//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animelist.Models.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titles()
        {
            this.TitlesGenres = new HashSet<TitlesGenres>();
            this.Users_PlannedTitles = new HashSet<Users_PlannedTitles>();
            this.UsersFavoriteTitles = new HashSet<UsersFavoriteTitles>();
        }
    
        public int TitleID { get; set; }
        public string TitleName { get; set; }
        public int TitleViews { get; set; }
        public Nullable<double> TitleRating { get; set; }
        public int TitleYear { get; set; }
        public string TitleType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string TitleStatus { get; set; }
        public string TitleDate { get; set; }
        public Nullable<int> TitleEpisodes { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitlesGenres> TitlesGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_PlannedTitles> Users_PlannedTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersFavoriteTitles> UsersFavoriteTitles { get; set; }
    }
}
